{% set name = "hpfrec" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hpfrec-{{ version }}.tar.gz
  sha256: 53ce6cb89517cd0ab822ea888a8bb9f07b5a5be46ea0df09c7f51ebc709940fb

build:
  skip: true  # [py<310 or win]
  number: 0

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - cython >=3.0.0,<4                     # [build_platform != target_platform]
    - numpy 1.25                            # [build_platform != target_platform and py<312]
    - numpy                                 # [build_platform != target_platform and py>=312]
    - scipy >=1.11.1                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cython >=3.0.0,<4
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - setuptools
    - wheel
    - pip
    - python
    - numpy 1.25  # [py<312]
    - numpy       # [py>=312]
    - scipy >=1.11.1
  run:
    - python
    - scipy >=1.11.1
    - pandas >=1

test:
  imports:
    - hpfrec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/david-cortes/hpfrec
  summary: Hierarchical Poisson matrix factorization for recommender systems
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdekstrand
